version: '3'

services:
  turtlebot-gazebo:
    # run the robot ros core as well as a headless gazebo simulation
    image: brean/ros-turtlebot3-gazebo:foxy
    tty: True
    container_name: ros-foxy
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        ROS_DISTRO: foxy
    environment: 
      - DISPLAY
      - "ROS_DISTRO=foxy"
      - NVIDIA_VISIBLE_DEVICES=all # for docker-nvidia2
      - NVIDIA_DRIVER_CAPABILITIES=all # for docker-nvidia2
    privileged: true  # for gazebo gui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro  # for gazebo gui
    networks:
      - turtlebot
    command: ["ros2", "launch", "turtlebot3_gazebo", "turtlebot3_world.launch.py"]

networks:
  turtlebot:
    name: turtlebot